services:
  - type: web
    name: attendance-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      # Database (Aiven MySQL)
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-ad3913c-attendx-123.h.aivencloud.com:23223/defaultdb?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
      - key: MYSQLUSER
        value: avnadmin
      - key: MYSQLPASSWORD
        value: AVNS_shZL_W32Nbun6gR0EZS

      # JWT Secrets
      - key: APP_JWT_SECRET
        value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - key: APP_QR_SECRET
        value: 8f93a1c2b3d4e5f678901234567890abcdef1234567890abcdef1234567890ab

      # Email (Gmail SMTP)
      - key: SPRING_MAIL_USERNAME
        value: kaushalgupta9640016@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: xlogvttjhzyndoxa
      - key: SPRING_MAIL_PORT
        value: "587"

      # Spring Profile
      - key: SPRING_PROFILES_ACTIVE
        value: prod
